version: "2.1"
services:
  aws-linux:
    container_name: aws-linux
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compose:/compose
# yum update
# amazon-linux-extras install docker
# sudo systemctl enable docker / status / start
# usermod -a -G docker ec2-user